CREATE TABLE tracks(
    ID INT NOT NULL IDENTITY,
    FOLDER_ID INT NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DATETIME TIMESTAMP NOT NULL,
    SOUTH DOUBLE NOT NULL,
    WEST DOUBLE NOT NULL,
    NORTH DOUBLE NOT NULL,
    EAST DOUBLE NOT NULL,
    GPX TEXT NOT NULL,

    FOREIGN KEY (FOLDER_ID) REFERENCES folders(ID)
);

CREATE UNIQUE INDEX tracks_folder_name ON tracks(FOLDER_ID,NAME);
