ALTER TABLE folders ADD (
    DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PUBDATE TIMESTAMP,
    BODY TEXT
);

CREATE INDEX folders_pubdate ON folders(PUBDATE);

CREATE TABLE tags(
    ID INT NOT NULL IDENTITY,
    LABEL VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX tags_tag ON tags(LABEL);

CREATE TABLE foldertags(
    FOLDER_ID INT NOT NULL,
    TAG_ID INT NOT NULL,

    PRIMARY KEY (FOLDER_ID,TAG_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES folders(ID),
    FOREIGN KEY (TAG_ID) REFERENCES tags(ID)
);

CREATE UNIQUE INDEX foldertags_tag_folder ON foldertags(TAG_ID,FOLDER_ID);
